#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

export DSE_METHOD=regret
export DSE_TAG="${DSE_TAG:-regret_scale_s20260730_n200_m384}"
export SAMPLES="${SAMPLES:-200}"
export SAMPLE_SEED="${SAMPLE_SEED:-20260730}"
export MAX_TOKENS="${MAX_TOKENS:-384}"
export TEMPERATURE="${TEMPERATURE:-0.7}"
export SEED="${SEED:-42}"
export MTP_TOKENS="${MTP_TOKENS:-6}"
export PROGRESS_EVERY="${PROGRESS_EVERY:-20}"

export REGRET_DIRECTION=expected_scale
export REGRET_SCALE_INITIAL="${REGRET_SCALE_INITIAL:-1.10}"
export REGRET_SCALE_INITIAL_BY_RELIABILITY=0
export REGRET_SCALE_CAUSAL_ONLY=0
export REGRET_SCALE_LEARNING_RATE="${REGRET_SCALE_LEARNING_RATE:-0.25}"
export REGRET_SCALE_DECAY="${REGRET_SCALE_DECAY:-0.90}"
export REGRET_SCALE_GAP_REFERENCE="${REGRET_SCALE_GAP_REFERENCE:-0.05}"
export REGRET_SCALE_NEWTON_CLIP="${REGRET_SCALE_NEWTON_CLIP:-0.20}"
export REGRET_SCALE_MIN="${REGRET_SCALE_MIN:-1.0}"
export REGRET_SCALE_MAX="${REGRET_SCALE_MAX:-1.25}"

exec "$PROJECT_DIR/scripts/run_gsm8k_regret_dse_point.sh"
