#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MTP_TOKENS="${MTP_TOKENS:-6}"
export REMTP_WORKER_CLS=remtp.worker.TargetModeRegretWorker
export REMTP_MODE_REGRET_MIN_TARGET_PROB="${MODE_REGRET_MIN_TARGET_PROB:-0.50}"
export REMTP_MODE_REGRET_PER_TOKEN_TV="${MODE_REGRET_PER_TOKEN_TV:-0.49}"
export REMTP_MODE_REGRET_BLOCK_TV="${MODE_REGRET_BLOCK_TV:-0.60}"
export REMTP_MODE_REGRET_DEBT_SLOPE="${MODE_REGRET_DEBT_SLOPE:-0.50}"
export REMTP_MODE_REGRET_DEPTH_SLOPE="${MODE_REGRET_DEPTH_SLOPE:-0.00}"
export REMTP_MODE_REGRET_ELIGIBILITY="${MODE_REGRET_ELIGIBILITY:-probability}"
export REMTP_MODE_REGRET_MIN_TOP1_MARGIN="${MODE_REGRET_MIN_TOP1_MARGIN:-0.00}"
export REMTP_MODE_REGRET_MARGIN_DEBT_SLOPE="${MODE_REGRET_MARGIN_DEBT_SLOPE:-0.50}"
export REMTP_MODE_REGRET_MARGIN_DEPTH_SLOPE="${MODE_REGRET_MARGIN_DEPTH_SLOPE:-0.00}"
export REMTP_MODE_REGRET_MAX_TARGET_RANK="${MODE_REGRET_MAX_TARGET_RANK:-4}"
export REMTP_MODE_REGRET_MAX_CANDIDATE_GAP="${MODE_REGRET_MAX_CANDIDATE_GAP:-0.50}"
export REMTP_MODE_REGRET_BAND_DEBT_SLOPE="${MODE_REGRET_BAND_DEBT_SLOPE:-0.75}"
export REMTP_MODE_REGRET_BAND_DEPTH_SLOPE="${MODE_REGRET_BAND_DEPTH_SLOPE:-0.00}"
export REMTP_MODE_REGRET_COMPILE="${MODE_REGRET_COMPILE:-1}"
export REMTP_MODE_REGRET_DIAGNOSTICS="${MODE_REGRET_DIAGNOSTICS:-0}"

exec "$PROJECT_DIR/scripts/serve_probabilistic_mtp.sh"
