#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_DIR/.venv/bin/activate"

export REMTP_TRACE=0
export ENFORCE_EAGER=0
export MTP_TOKENS="${MTP_TOKENS:-6}"
export MTP_REJECTION_SAMPLE_METHOD=probabilistic
export REMTP_WORKER_CLS=remtp.worker.RegretFeedbackMTPWorker

if [[ "$MTP_TOKENS" != "6" ]]; then
  echo "Budget-Induced Regret Feedback requires MTP_TOKENS=6." >&2
  exit 2
fi

# The historical default remains unchanged. Current-block experiments may
# select tv_debt_control while future-only scale/top-1 feedback stays an
# optional, low-cost ablation.
export REMTP_TA_VARIANT="${TARGET_ANCHORED_VARIANT:-tv_hidden_veto}"
export REMTP_TA_EXPECTED_DRAFT_TOKENS="$MTP_TOKENS"
export REMTP_CACTUS_DELTA="${CACTUS_DELTA:-1.0}"
export REMTP_TA_HEAD_RELIABILITY="${HEAD_RELIABILITY:-1.0,0.85,0.70,0.55,0.40,0.30}"
export REMTP_TA_TARGET_LOG_GAP_SCALE="${TARGET_LOG_GAP_SCALE:-2.0}"
export REMTP_TA_MAX_TARGET_LOG_GAP="${MAX_TARGET_LOG_GAP:-8.0}"
export REMTP_TA_FUTURE_VETO_FLOOR="${FUTURE_VETO_FLOOR:-0.20}"
export REMTP_TA_HIDDEN_RELIABILITY_FLOOR="${HIDDEN_RELIABILITY_FLOOR:-0.25}"
export REMTP_TA_USE_PREFIX_VALUE="${USE_PREFIX_VALUE:-1}"
export REMTP_TA_DEBT_POSITION_LIMIT="${DEBT_POSITION_LIMIT:-0.35}"
export REMTP_TA_DEBT_BLOCK_LIMIT="${DEBT_BLOCK_LIMIT:-1.20}"
export REMTP_TA_DEBT_SOFT_LOG_GAP="${DEBT_SOFT_LOG_GAP:-2.0}"
export REMTP_TA_DEBT_HARD_LOG_GAP="${DEBT_HARD_LOG_GAP:-6.0}"
export REMTP_TA_DEBT_MAX_POSITION_TV="${DEBT_MAX_POSITION_TV:-0.15}"
export REMTP_TA_DEBT_MAX_CACTUS_RATIO="${DEBT_MAX_CACTUS_RATIO:-2.0}"
export REMTP_TA_DEBT_FALLBACK="${DEBT_FALLBACK:-strict}"
export REMTP_TA_AUDIT_INTERVAL="${TARGET_ANCHORED_AUDIT_INTERVAL:-0}"
export REMTP_TA_DIAGNOSTICS="${TARGET_ANCHORED_DIAGNOSTICS:-0}"
export REMTP_TA_COMPILE="${TARGET_ANCHORED_COMPILE:-1}"

# Cross-block regret feedback. Only the copied root condition of the next MTP
# block is changed; target logits/KV and target-anchored verification are not.
export REMTP_REGRET_EXPECTED_DRAFT_TOKENS="$MTP_TOKENS"
export REMTP_REGRET_DIRECTION="${REGRET_DIRECTION:-token}"
export REMTP_REGRET_TOP_K="${REGRET_TOP_K:-16}"
export REMTP_REGRET_COMPATIBILITY_TOP_K="${REGRET_COMPATIBILITY_TOP_K:-32}"
export REMTP_REGRET_COMPATIBILITY_MODE="${REGRET_COMPATIBILITY_MODE:-relative}"
export REMTP_REGRET_COMPATIBILITY_SOURCE="${REGRET_COMPATIBILITY_SOURCE:-cached}"
export REMTP_REGRET_ALPHA="${REGRET_ALPHA:-0.03}"
export REMTP_REGRET_STRENGTH_REFERENCE="${REGRET_STRENGTH_REFERENCE:-0.0}"
export REMTP_REGRET_SCALE_LEARNING_RATE="${REGRET_SCALE_LEARNING_RATE:-0.50}"
export REMTP_REGRET_SCALE_DECAY="${REGRET_SCALE_DECAY:-0.90}"
export REMTP_REGRET_SCALE_GAP_REFERENCE="${REGRET_SCALE_GAP_REFERENCE:-0.05}"
export REMTP_REGRET_SCALE_NEWTON_CLIP="${REGRET_SCALE_NEWTON_CLIP:-0.20}"
export REMTP_REGRET_SCALE_MIN="${REGRET_SCALE_MIN:-0.75}"
export REMTP_REGRET_SCALE_MAX="${REGRET_SCALE_MAX:-1.25}"
export REMTP_REGRET_SCALE_INITIAL="${REGRET_SCALE_INITIAL:-1.0}"
export REMTP_REGRET_SCALE_INITIAL_BY_RELIABILITY="${REGRET_SCALE_INITIAL_BY_RELIABILITY:-0}"
export REMTP_REGRET_SCALE_CAUSAL_ONLY="${REGRET_SCALE_CAUSAL_ONLY:-0}"
export REMTP_REGRET_TOP1_BIAS_INITIAL="${REGRET_TOP1_BIAS_INITIAL:-0.25}"
export REMTP_REGRET_TOP1_BIAS_LEARNING_RATE="${REGRET_TOP1_BIAS_LEARNING_RATE:-0.25}"
export REMTP_REGRET_TOP1_BIAS_DECAY="${REGRET_TOP1_BIAS_DECAY:-0.90}"
export REMTP_REGRET_TOP1_BIAS_CLIP="${REGRET_TOP1_BIAS_CLIP:-0.75}"
export REMTP_REGRET_REPETITION_NGRAM_SIZE="${REGRET_REPETITION_NGRAM_SIZE:-4}"
export REMTP_REGRET_REPETITION_PENALTY="${REGRET_REPETITION_PENALTY:-1.0}"
export REMTP_REGRET_REPETITION_DEBT_REFERENCE="${REGRET_REPETITION_DEBT_REFERENCE:-0.25}"
export REMTP_REGRET_ADAPTIVE_MIN_DEPTH="${REGRET_ADAPTIVE_MIN_DEPTH:-4}"
export REMTP_REGRET_ADAPTIVE_DEPTH_BLOCKS="${REGRET_ADAPTIVE_DEPTH_BLOCKS:-2}"
export REMTP_REGRET_ADAPTIVE_DEPTH_TRIGGER="${REGRET_ADAPTIVE_DEPTH_TRIGGER:-0.25}"
export REMTP_REGRET_ROOT_ANCHOR_MIX="${REGRET_ROOT_ANCHOR_MIX:-0.25}"
export REMTP_REGRET_ROOT_ANCHOR_REFERENCE="${REGRET_ROOT_ANCHOR_REFERENCE:-0.50}"
export REMTP_REGRET_ROOT_ANCHOR_MIN_CONFIDENCE="${REGRET_ROOT_ANCHOR_MIN_CONFIDENCE:-0.50}"
export REMTP_REGRET_VOCAB_BIAS_SCALE="${REGRET_VOCAB_BIAS_SCALE:-0.05}"
export REMTP_REGRET_VOCAB_BIAS_CLIP="${REGRET_VOCAB_BIAS_CLIP:-2.0}"
export REMTP_REGRET_VOCAB_BIAS_TOP_K="${REGRET_VOCAB_BIAS_TOP_K:-32}"
export REMTP_REGRET_VOCAB_HEAD_MAP="${REGRET_VOCAB_HEAD_MAP:-0,0,4,2,3,1}"
export REMTP_REGRET_VOCAB_ROUTE_DECAY="${REGRET_VOCAB_ROUTE_DECAY:-0.50}"
export REMTP_REGRET_VOCAB_ROUTE_MIN_GAIN="${REGRET_VOCAB_ROUTE_MIN_GAIN:-0.0}"
export REMTP_REGRET_VOCAB_ROUTE_PRIOR_GAIN="${REGRET_VOCAB_ROUTE_PRIOR_GAIN:-0.0}"
export REMTP_REGRET_VOCAB_ROUTE_GAIN_CLIP="${REGRET_VOCAB_ROUTE_GAIN_CLIP:-0.001}"
export REMTP_REGRET_FUSION_GATE_THRESHOLD="${REGRET_FUSION_GATE_THRESHOLD:-0.50}"
export REMTP_REGRET_HIDDEN_CONSISTENCY_THRESHOLD="${REGRET_HIDDEN_CONSISTENCY_THRESHOLD:-0.0}"
export REMTP_REGRET_HIDDEN_CONFIRMATION_BLOCKS="${REGRET_HIDDEN_CONFIRMATION_BLOCKS:-2}"
export REMTP_REGRET_HIDDEN_UNCONFIRMED_SCALE="${REGRET_HIDDEN_UNCONFIRMED_SCALE:-0.50}"
export REMTP_REGRET_VERIFIER_RISK_STRENGTH="${REGRET_VERIFIER_RISK_STRENGTH:-2.0}"
export REMTP_REGRET_VERIFIER_RISK_REFERENCE="${REGRET_VERIFIER_RISK_REFERENCE:-0.25}"
export REMTP_REGRET_VERIFIER_POLICY="${REGRET_VERIFIER_POLICY:-heuristic}"
export REMTP_REGRET_VERIFIER_CACTUS_MIX="${REGRET_VERIFIER_CACTUS_MIX:-1.0}"
export REMTP_REGRET_VERIFIER_BUDGET_SLOPE="${REGRET_VERIFIER_BUDGET_SLOPE:-0.4}"
export REMTP_REGRET_VERIFIER_TAIL_THRESHOLD="${REGRET_VERIFIER_TAIL_THRESHOLD:-0.8}"
export REMTP_REGRET_TOKEN_DECAY="${REGRET_TOKEN_DECAY:-0.90}"
export REMTP_REGRET_REJECTION_RESET="${REGRET_REJECTION_RESET:-0.25}"
export REMTP_REGRET_MAX_IDLE_BLOCKS="${REGRET_MAX_IDLE_BLOCKS:-2}"
export REMTP_REGRET_INCOMPATIBLE_DECAY="${REGRET_INCOMPATIBLE_DECAY:-0.50}"
export REMTP_REGRET_HEAD_RELIABILITY="${HEAD_RELIABILITY:-1.0,0.85,0.70,0.55,0.40,0.30}"
export REMTP_REGRET_AUDIT_INTERVAL="${REGRET_AUDIT_INTERVAL:-100}"
export REMTP_REGRET_DIAGNOSTICS="${REGRET_DIAGNOSTICS:-0}"

# Qwen3.5's GDN Triton kernel cannot be captured safely in this pinned stack.
if [[ -z "${REMTP_COMPILATION_CONFIG:-}" ]]; then
  export REMTP_COMPILATION_CONFIG='{"cudagraph_mode":"NONE"}'
fi

echo "[ReMTP][Regret] mtp_tokens=$MTP_TOKENS direction=$REMTP_REGRET_DIRECTION alpha=$REMTP_REGRET_ALPHA decay=$REMTP_REGRET_TOKEN_DECAY scale_lr=$REMTP_REGRET_SCALE_LEARNING_RATE scale_decay=$REMTP_REGRET_SCALE_DECAY"
exec "$PROJECT_DIR/scripts/serve.sh"
