#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MTP_TOKENS="${MTP_TOKENS:-6}"
export REMTP_WORKER_CLS=remtp.worker.ExactTVRegretRouterWorker
export TARGET_ANCHORED_VARIANT=tv_router
export REMTP_ROUTER_MODE="${REGRET_ROUTER_MODE:-identity}"
export REMTP_ROUTER_CHECKPOINT="${REGRET_ROUTER_CHECKPOINT:-}"
export REMTP_ROUTER_EXPECTED_DRAFT_TOKENS="$MTP_TOKENS"
export REMTP_ROUTER_HEAD_RELIABILITY="${HEAD_RELIABILITY:-1.0,0.85,0.70,0.55,0.40,0.30}"
export REMTP_ROUTER_TOP_K="${REGRET_ROUTER_TOP_K:-32}"
export REMTP_ROUTER_DEBT_DECAY="${REGRET_ROUTER_DEBT_DECAY:-0.90}"
export REMTP_ROUTER_DEBT_REFERENCE="${REGRET_ROUTER_DEBT_REFERENCE:-0.05}"
export REMTP_ROUTER_REJECTION_RESET="${REGRET_ROUTER_REJECTION_RESET:-0.0}"
export REMTP_ROUTER_MAX_DIRECTION_STRENGTH="${REGRET_ROUTER_MAX_DIRECTION_STRENGTH:-0.03}"
export REMTP_ROUTER_MAX_LOGIT_SCALE="${REGRET_ROUTER_MAX_LOGIT_SCALE:-0.08}"
export REMTP_ROUTER_MAX_BUDGET_REDUCTION="${REGRET_ROUTER_MAX_BUDGET_REDUCTION:-0.50}"
export REMTP_ROUTER_COLLECT_DIR="${REGRET_ROUTER_COLLECT_DIR:-}"
export REMTP_ROUTER_COLLECTION_ID="${REGRET_ROUTER_COLLECTION_ID:-}"
export REMTP_ROUTER_COLLECT_SHARD_SIZE="${REGRET_ROUTER_COLLECT_SHARD_SIZE:-128}"
export REMTP_ROUTER_AUDIT_INTERVAL="${REGRET_ROUTER_AUDIT_INTERVAL:-0}"
export REMTP_ROUTER_DIAGNOSTICS="${REGRET_ROUTER_DIAGNOSTICS:-0}"

if [[ "$REMTP_ROUTER_MODE" == "learned" && -z "$REMTP_ROUTER_CHECKPOINT" ]]; then
  echo "REGRET_ROUTER_CHECKPOINT is required in learned mode." >&2
  exit 2
fi
if [[ "$REMTP_ROUTER_MODE" == "collect" && -z "$REMTP_ROUTER_COLLECT_DIR" ]]; then
  echo "REGRET_ROUTER_COLLECT_DIR is required in collect mode." >&2
  exit 2
fi

echo "[ReMTP][RegretRouter] mode=$REMTP_ROUTER_MODE checkpoint=${REMTP_ROUTER_CHECKPOINT:-none}"
exec "$PROJECT_DIR/scripts/serve_target_anchored_mtp.sh"
