#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# More total TV than scheme12_joint, but 85% is reserved for target-anchored
# rank-2/gap-0.75 candidates. Broader rescues share only a small risk pool.
export RISK_VARIANT=scheme12_anchored
export RISK_MAX_RANK="${RISK_MAX_RANK:-8}"
export RISK_BASE_GAP="${RISK_BASE_GAP:-1.50}"
export RISK_AMBIGUITY_SCALE="${RISK_AMBIGUITY_SCALE:-0.65}"
export RISK_THRESHOLD_POSITION_SCALE="${RISK_THRESHOLD_POSITION_SCALE:-0.20}"
export RISK_RANK_POSITION_SCALE="${RISK_RANK_POSITION_SCALE:-0.25}"
export RISK_POSITION_SCALE="${RISK_POSITION_SCALE:-0.35}"
export RISK_CONFIDENCE_SCALE="${RISK_CONFIDENCE_SCALE:-0.40}"
export RISK_MTP_CONFIDENCE_FLOOR="${RISK_MTP_CONFIDENCE_FLOOR:-0.03}"
export RISK_PER_TOKEN_TV="${RISK_PER_TOKEN_TV:-0.55}"
export RISK_BLOCK_TV="${RISK_BLOCK_TV:-1.85}"
export JOINT_RISK_MASS="${JOINT_RISK_MASS:-0.75}"
export JOINT_RISK_TEMPERATURE="${JOINT_RISK_TEMPERATURE:-1.00}"
export JOINT_PREFIX_WEIGHT="${JOINT_PREFIX_WEIGHT:-1.50}"
export JOINT_CORE_RANK="${JOINT_CORE_RANK:-2}"
export JOINT_CORE_GAP="${JOINT_CORE_GAP:-0.75}"
export JOINT_CORE_FRACTION="${JOINT_CORE_FRACTION:-0.85}"
export JOINT_EXPLORE_MIN_CHECKS="${JOINT_EXPLORE_MIN_CHECKS:-2}"
export JOINT_SUPPORT_POWER="${JOINT_SUPPORT_POWER:-1.25}"
export JOINT_EXPLORE_RISK_MULTIPLIER="${JOINT_EXPLORE_RISK_MULTIPLIER:-2.50}"
export SENTINEL_MAX_GAP="${SENTINEL_MAX_GAP:-2.00}"
export SENTINEL_MTP_FLOOR="${SENTINEL_MTP_FLOOR:-0.005}"
export SENTINEL_HEAD_MASS_FLOOR="${SENTINEL_HEAD_MASS_FLOOR:-0.05}"
export SENTINEL_MIN_CHECKS="${SENTINEL_MIN_CHECKS:-1}"
export SENTINEL_SOFT_FLOOR="${SENTINEL_SOFT_FLOOR:-0.55}"
export SENTINEL_LAST_GAP_SCALE="${SENTINEL_LAST_GAP_SCALE:-1.00}"
export RISK_DEBT_SCALE="${RISK_DEBT_SCALE:-0.30}"
export RISK_ADAPTIVE_DRAFT="${RISK_ADAPTIVE_DRAFT:-0}"

exec "$PROJECT_DIR/scripts/serve_risk_entropy_mtp.sh"
