#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MTP_TOKENS="${MTP_TOKENS:-6}"
export REGRET_DIRECTION=expected_scale_tv
export REGRET_SCALE_INITIAL="${REGRET_SCALE_INITIAL:-1.0}"
export REGRET_SCALE_INITIAL_BY_RELIABILITY=0
export REGRET_SCALE_CAUSAL_ONLY=0
export REGRET_SCALE_LEARNING_RATE="${REGRET_SCALE_LEARNING_RATE:-0.50}"
export REGRET_SCALE_DECAY="${REGRET_SCALE_DECAY:-0.90}"
export REGRET_SCALE_GAP_REFERENCE="${REGRET_SCALE_GAP_REFERENCE:-0.05}"
export REGRET_SCALE_MIN="${REGRET_SCALE_MIN:-0.90}"
export REGRET_SCALE_MAX="${REGRET_SCALE_MAX:-1.10}"

exec "$PROJECT_DIR/scripts/serve_regret_feedback_mtp.sh"
