#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_DIR/.venv/bin/activate"

export REMTP_TRACE=0
export ENFORCE_EAGER=0
export MTP_TOKENS="${MTP_TOKENS:-6}"
export MTP_REJECTION_SAMPLE_METHOD=probabilistic
export REMTP_WORKER_CLS=remtp.worker.CactusRegretMTPWorker
export REMTP_CACTUS_DELTA="${CACTUS_DELTA:-1.0}"
export REMTP_CACTUS_DIAGNOSTICS="${CACTUS_DIAGNOSTICS:-0}"

if [[ "$MTP_TOKENS" != "6" ]]; then
  echo "Cactus regret feedback currently requires MTP_TOKENS=6." >&2
  exit 2
fi

export REMTP_CACTUS_REGRET_EXPECTED_DRAFT_TOKENS="$MTP_TOKENS"
export REMTP_CACTUS_REGRET_TOP_K="${CACTUS_REGRET_TOP_K:-16}"
export REMTP_CACTUS_REGRET_ALPHA="${CACTUS_REGRET_ALPHA:-0.03}"
export REMTP_CACTUS_REGRET_STRENGTH_REFERENCE="${CACTUS_REGRET_STRENGTH_REFERENCE:-0.10}"
export REMTP_CACTUS_REGRET_DEPTH_DECAY="${CACTUS_REGRET_DEPTH_DECAY:-0.90}"
export REMTP_CACTUS_REGRET_RESPONSIBILITY="${CACTUS_REGRET_RESPONSIBILITY:-posterior}"
export REMTP_CACTUS_REGRET_INJECTION_SITE="${CACTUS_REGRET_INJECTION_SITE:-head1}"
export REMTP_CACTUS_REGRET_RESIDUAL_SPACE="${CACTUS_REGRET_RESIDUAL_SPACE:-output}"
export REMTP_CACTUS_REGRET_AUDIT_INTERVAL="${CACTUS_REGRET_AUDIT_INTERVAL:-0}"
export REMTP_CACTUS_REGRET_DIAGNOSTICS="${CACTUS_REGRET_DIAGNOSTICS:-0}"

if [[ -z "${REMTP_COMPILATION_CONFIG:-}" ]]; then
  export REMTP_COMPILATION_CONFIG='{"cudagraph_mode":"NONE"}'
fi

echo "[ReMTP][CactusRegret] alpha=$REMTP_CACTUS_REGRET_ALPHA top_k=$REMTP_CACTUS_REGRET_TOP_K responsibility=$REMTP_CACTUS_REGRET_RESPONSIBILITY injection=$REMTP_CACTUS_REGRET_INJECTION_SITE residual=$REMTP_CACTUS_REGRET_RESIDUAL_SPACE"
exec "$PROJECT_DIR/scripts/serve.sh"
