#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MTP_TOKENS="${MTP_TOKENS:-6}"
export REMTP_WORKER_CLS=remtp.worker.RiskEntropyMTPWorker
export REMTP_RISK_VARIANT="${RISK_VARIANT:-scheme1}"
export REMTP_RISK_EXPECTED_DRAFT_TOKENS="$MTP_TOKENS"
export REMTP_RISK_MAX_RANK="${RISK_MAX_RANK:-8}"
export REMTP_RISK_SCHEME2_RANK="${RISK_SCHEME2_RANK:-4}"
export REMTP_RISK_TOP_M="${RISK_TOP_M:-4}"
export REMTP_RISK_BASE_GAP="${RISK_BASE_GAP:-0.90}"
export REMTP_RISK_AMBIGUITY_SCALE="${RISK_AMBIGUITY_SCALE:-0.60}"
export REMTP_RISK_THRESHOLD_POSITION_SCALE="${RISK_THRESHOLD_POSITION_SCALE:-0.35}"
export REMTP_RISK_RANK_POSITION_SCALE="${RISK_RANK_POSITION_SCALE:-0.50}"
export REMTP_RISK_BUDGET="${RISK_BUDGET:-2.40}"
export REMTP_RISK_POSITION_SCALE="${RISK_POSITION_SCALE:-0.50}"
export REMTP_RISK_CONFIDENCE_SCALE="${RISK_CONFIDENCE_SCALE:-0.50}"
export REMTP_RISK_MTP_CONFIDENCE_FLOOR="${RISK_MTP_CONFIDENCE_FLOOR:-0.05}"
export REMTP_CACTUS_DELTA="${CACTUS_DELTA:-1.0}"
export REMTP_RISK_PER_TOKEN_TV="${RISK_PER_TOKEN_TV:-0.25}"
export REMTP_RISK_BLOCK_TV="${RISK_BLOCK_TV:-0.90}"
export REMTP_JOINT_RISK_MASS="${JOINT_RISK_MASS:-0.90}"
export REMTP_JOINT_RISK_TEMPERATURE="${JOINT_RISK_TEMPERATURE:-1.50}"
export REMTP_JOINT_PREFIX_WEIGHT="${JOINT_PREFIX_WEIGHT:-1.00}"
export REMTP_JOINT_CORE_RANK="${JOINT_CORE_RANK:-2}"
export REMTP_JOINT_CORE_GAP="${JOINT_CORE_GAP:-0.75}"
export REMTP_JOINT_CORE_FRACTION="${JOINT_CORE_FRACTION:-0.85}"
export REMTP_JOINT_EXPLORE_MIN_CHECKS="${JOINT_EXPLORE_MIN_CHECKS:-2}"
export REMTP_JOINT_SUPPORT_POWER="${JOINT_SUPPORT_POWER:-1.00}"
export REMTP_JOINT_EXPLORE_RISK_MULTIPLIER="${JOINT_EXPLORE_RISK_MULTIPLIER:-2.00}"
export REMTP_SENTINEL_MAX_GAP="${SENTINEL_MAX_GAP:-1.00}"
export REMTP_SENTINEL_MTP_FLOOR="${SENTINEL_MTP_FLOOR:-0.02}"
export REMTP_SENTINEL_HEAD_MASS_FLOOR="${SENTINEL_HEAD_MASS_FLOOR:-0.10}"
export REMTP_SENTINEL_MIN_CHECKS="${SENTINEL_MIN_CHECKS:-2}"
export REMTP_SENTINEL_SOFT_FLOOR="${SENTINEL_SOFT_FLOOR:-1.00}"
export REMTP_SENTINEL_LAST_GAP_SCALE="${SENTINEL_LAST_GAP_SCALE:-0.70}"
export REMTP_FINAL_GAP_FLOOR="${REMTP_FINAL_GAP_FLOOR:-1.15}"
export REMTP_FINAL_MARGIN_TEMPERATURE="${REMTP_FINAL_MARGIN_TEMPERATURE:-0.75}"
export REMTP_FINAL_RISKY_RANK="${REMTP_FINAL_RISKY_RANK:-4}"
export REMTP_FINAL_RISKY_GAP="${REMTP_FINAL_RISKY_GAP:-1.20}"
export REMTP_FINAL_RISKY_MIN_CHECKS="${REMTP_FINAL_RISKY_MIN_CHECKS:-2}"
export REMTP_FINAL_PREFIX_WEIGHT="${REMTP_FINAL_PREFIX_WEIGHT:-0.75}"
export REMTP_FINAL_SUPPORT_TEMPERATURE="${REMTP_FINAL_SUPPORT_TEMPERATURE:-1.00}"
export REMTP_BLOCK_CONTINUATION_GAP="${REMTP_BLOCK_CONTINUATION_GAP:-2.50}"
export REMTP_BLOCK_CONTINUATION_SUPPORT="${REMTP_BLOCK_CONTINUATION_SUPPORT:-0.65}"
export REMTP_BLOCK_CONTINUATION_REGRET="${REMTP_BLOCK_CONTINUATION_REGRET:-0.50}"
export REMTP_BLOCK_CONTINUATION_HORIZON="${REMTP_BLOCK_CONTINUATION_HORIZON:-3}"
export REMTP_RISK_DEBT_DECAY="${RISK_DEBT_DECAY:-0.80}"
export REMTP_RISK_DEBT_SCALE="${RISK_DEBT_SCALE:-0.75}"
export REMTP_RISK_ADAPTIVE_DRAFT="${RISK_ADAPTIVE_DRAFT:-1}"
export REMTP_RISK_MEDIUM_DRAFT_DEPTH="${RISK_MEDIUM_DRAFT_DEPTH:-4}"
export REMTP_RISK_SHORT_DRAFT_DEPTH="${RISK_SHORT_DRAFT_DEPTH:-2}"
export REMTP_RISK_MEDIUM_DEBT="${RISK_MEDIUM_DEBT:-0.50}"
export REMTP_RISK_HIGH_DEBT="${RISK_HIGH_DEBT:-1.50}"
export REMTP_RISK_DIAGNOSTICS="${RISK_DIAGNOSTICS:-0}"
export REMTP_RISK_AUDIT_PATH="${RISK_AUDIT_PATH:-}"
export REMTP_RISK_AUDIT_DATASET="${RISK_AUDIT_DATASET:-unknown}"

if [[ "$REMTP_RISK_ADAPTIVE_DRAFT" == "1" \
  && ( "$REMTP_RISK_VARIANT" == "scheme2" \
    || "$REMTP_RISK_VARIANT" == "scheme12" \
    || "$REMTP_RISK_VARIANT" == "scheme2_relaxed" \
    || "$REMTP_RISK_VARIANT" == "scheme12_joint" \
    || "$REMTP_RISK_VARIANT" == "scheme12_anchored" \
    || "$REMTP_RISK_VARIANT" == "remtp" \
    || "$REMTP_RISK_VARIANT" == "remtp_block" ) ]]; then
  # Variable draft counts currently require vLLM's scheduler-visible CPU path.
  export ASYNC_SCHEDULING=0
fi

exec "$PROJECT_DIR/scripts/serve_probabilistic_mtp.sh"
