#!/usr/bin/env bash
# Serve FastMTP with dynamic tree + target-dominant relaxation
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

MODEL_PATH="${MODEL_PATH:-$PROJECT_DIR/models/FastMTP}"
SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-TencentBAC/FastMTP}"
PORT="${PORT:-8000}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-8192}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.90}"
TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-1}"
ENFORCE_EAGER="${ENFORCE_EAGER:-1}"
NO_ASYNC_SCHEDULING="${NO_ASYNC_SCHEDULING:-1}"

# Tree construction parameters
TREE_RUN_DIR="${TREE_RUN_DIR:-}"
REMTP_TREE_AUDIT_JSONL="${REMTP_TREE_AUDIT_JSONL:-}"
REMTP_TREE_AUDIT_DETAIL="${REMTP_TREE_AUDIT_DETAIL:-0}"
REMTP_TREE_TRACE="${REMTP_TREE_TRACE:-0}"
REMTP_DYNAMIC_TREE_MAX_DEPTH="${REMTP_DYNAMIC_TREE_MAX_DEPTH:-3}"
REMTP_DYNAMIC_TREE_MAX_NODES="${REMTP_DYNAMIC_TREE_MAX_NODES:-6}"
REMTP_DYNAMIC_TREE_ADAPTIVE_BASE_NODES="${REMTP_DYNAMIC_TREE_ADAPTIVE_BASE_NODES:-0}"
REMTP_DYNAMIC_TREE_ADAPTIVE_ENTROPY_THRESHOLD="${REMTP_DYNAMIC_TREE_ADAPTIVE_ENTROPY_THRESHOLD:-1.0}"
REMTP_DYNAMIC_TREE_MAX_CHILDREN="${REMTP_DYNAMIC_TREE_MAX_CHILDREN:-2}"
REMTP_DYNAMIC_TREE_MIN_SIBLING_RATIO="${REMTP_DYNAMIC_TREE_MIN_SIBLING_RATIO:-0.25}"
REMTP_DYNAMIC_TREE_TAU_MIN="${REMTP_DYNAMIC_TREE_TAU_MIN:-0.02}"
REMTP_DYNAMIC_TREE_KAPPA="${REMTP_DYNAMIC_TREE_KAPPA:-1.0}"
REMTP_DYNAMIC_TREE_MU="${REMTP_DYNAMIC_TREE_MU:-0.5}"
REMTP_DYNAMIC_TREE_ETA="${REMTP_DYNAMIC_TREE_ETA:-0.25}"
REMTP_DYNAMIC_TREE_ALLOCATION="${REMTP_DYNAMIC_TREE_ALLOCATION:-geometric}"
REMTP_DYNAMIC_TREE_RANK_PENALTY="${REMTP_DYNAMIC_TREE_RANK_PENALTY:-2.0}"
REMTP_DYNAMIC_TREE_ALPHA="${REMTP_DYNAMIC_TREE_ALPHA:-0.5}"
REMTP_DYNAMIC_TREE_TAU_RELAX="${REMTP_DYNAMIC_TREE_TAU_RELAX:-0.7}"
REMTP_DYNAMIC_TREE_SUPPORT_MODE="${REMTP_DYNAMIC_TREE_SUPPORT_MODE:-relative}"
REMTP_DYNAMIC_TREE_PROPOSAL_SUPPORT_RATIO="${REMTP_DYNAMIC_TREE_PROPOSAL_SUPPORT_RATIO:-1.0}"
REMTP_DYNAMIC_TREE_CONFIRMATION_MIN_RELATIVE="${REMTP_DYNAMIC_TREE_CONFIRMATION_MIN_RELATIVE:-0.05}"
REMTP_DYNAMIC_TREE_CACTUS_DELTA="${REMTP_DYNAMIC_TREE_CACTUS_DELTA:-1.0}"
REMTP_DYNAMIC_TREE_CACTUS_TARGET_WEIGHT="${REMTP_DYNAMIC_TREE_CACTUS_TARGET_WEIGHT:-0.25}"
REMTP_DYNAMIC_TREE_MAX_GUIDED_RESCUES="${REMTP_DYNAMIC_TREE_MAX_GUIDED_RESCUES:-1}"
REMTP_DYNAMIC_TREE_RESCUE_SCORE_THRESHOLD="${REMTP_DYNAMIC_TREE_RESCUE_SCORE_THRESHOLD:-0.35}"
REMTP_DYNAMIC_TREE_RESCUE_DEPTH_PENALTY="${REMTP_DYNAMIC_TREE_RESCUE_DEPTH_PENALTY:-0.0}"
REMTP_DYNAMIC_TREE_RESCUE_CONTINUATION_DISCOUNT="${REMTP_DYNAMIC_TREE_RESCUE_CONTINUATION_DISCOUNT:-0.0}"
REMTP_DYNAMIC_TREE_RESCUE_CONTINUATION_MIN_DEPTH="${REMTP_DYNAMIC_TREE_RESCUE_CONTINUATION_MIN_DEPTH:-2}"
REMTP_DYNAMIC_TREE_RESCUE_MARGIN_REFERENCE="${REMTP_DYNAMIC_TREE_RESCUE_MARGIN_REFERENCE:-0.0}"
REMTP_DYNAMIC_TREE_RESCUE_MARGIN_PENALTY="${REMTP_DYNAMIC_TREE_RESCUE_MARGIN_PENALTY:-0.0}"
REMTP_DYNAMIC_TREE_BETA="${REMTP_DYNAMIC_TREE_BETA:-0.5}"
REMTP_DYNAMIC_TREE_PATH_TEMPERATURE="${REMTP_DYNAMIC_TREE_PATH_TEMPERATURE:-0.3}"
REMTP_DYNAMIC_TREE_PATH_SELECTION="${REMTP_DYNAMIC_TREE_PATH_SELECTION:-longest}"
REMTP_DYNAMIC_TREE_FRONTIER_RESCUE="${REMTP_DYNAMIC_TREE_FRONTIER_RESCUE:-1}"
REMTP_DYNAMIC_TREE_RESCUE_DELTA="${REMTP_DYNAMIC_TREE_RESCUE_DELTA:-0.5}"
REMTP_DYNAMIC_TREE_RESCUE_MIN_RELATIVE="${REMTP_DYNAMIC_TREE_RESCUE_MIN_RELATIVE:-0.1}"
REMTP_DYNAMIC_TREE_RESCUE_MIN_TARGET_PROB="${REMTP_DYNAMIC_TREE_RESCUE_MIN_TARGET_PROB:-0.001}"
REMTP_DYNAMIC_TREE_EOS_THRESHOLD="${REMTP_DYNAMIC_TREE_EOS_THRESHOLD:-0.5}"

if [[ ! -f "$MODEL_PATH/config.json" ]]; then
  echo "Error: FastMTP model not found at $MODEL_PATH" >&2
  echo "Download it with: ./scripts/download_fastmtp.sh" >&2
  exit 2
fi

# Note: FastMTP uses MiMo custom code (modeling_mimo.py)
# Dynamic tree attention is currently implemented for MiMo architecture
# This should work since FastMTP is based on MiMo-7B-RL

WORKER_CLS="remtp.fastmtp_worker.FastMTPDynamicTreeWorker"

EXTRA_ARGS=()
[[ "$ENFORCE_EAGER" == "1" ]] && EXTRA_ARGS+=(--enforce-eager)
[[ "$NO_ASYNC_SCHEDULING" == "1" ]] && EXTRA_ARGS+=(--no-async-scheduling)
EXTRA_ARGS+=(--trust-remote-code)

# Export tree parameters
export TREE_RUN_DIR
export REMTP_TREE_AUDIT_JSONL
export REMTP_TREE_AUDIT_DETAIL
export REMTP_TREE_TRACE
export REMTP_DYNAMIC_TREE_MAX_DEPTH
export REMTP_DYNAMIC_TREE_MAX_NODES
export REMTP_DYNAMIC_TREE_ADAPTIVE_BASE_NODES
export REMTP_DYNAMIC_TREE_ADAPTIVE_ENTROPY_THRESHOLD
export REMTP_DYNAMIC_TREE_MAX_CHILDREN
export REMTP_DYNAMIC_TREE_MIN_SIBLING_RATIO
export REMTP_DYNAMIC_TREE_TAU_MIN
export REMTP_DYNAMIC_TREE_KAPPA
export REMTP_DYNAMIC_TREE_MU
export REMTP_DYNAMIC_TREE_ETA
export REMTP_DYNAMIC_TREE_ALLOCATION
export REMTP_DYNAMIC_TREE_RANK_PENALTY
export REMTP_DYNAMIC_TREE_ALPHA
export REMTP_DYNAMIC_TREE_TAU_RELAX
export REMTP_DYNAMIC_TREE_SUPPORT_MODE
export REMTP_DYNAMIC_TREE_PROPOSAL_SUPPORT_RATIO
export REMTP_DYNAMIC_TREE_CONFIRMATION_MIN_RELATIVE
export REMTP_DYNAMIC_TREE_CACTUS_DELTA
export REMTP_DYNAMIC_TREE_CACTUS_TARGET_WEIGHT
export REMTP_DYNAMIC_TREE_MAX_GUIDED_RESCUES
export REMTP_DYNAMIC_TREE_RESCUE_SCORE_THRESHOLD
export REMTP_DYNAMIC_TREE_RESCUE_DEPTH_PENALTY
export REMTP_DYNAMIC_TREE_RESCUE_CONTINUATION_DISCOUNT
export REMTP_DYNAMIC_TREE_RESCUE_CONTINUATION_MIN_DEPTH
export REMTP_DYNAMIC_TREE_RESCUE_MARGIN_REFERENCE
export REMTP_DYNAMIC_TREE_RESCUE_MARGIN_PENALTY
export REMTP_DYNAMIC_TREE_BETA
export REMTP_DYNAMIC_TREE_PATH_TEMPERATURE
export REMTP_DYNAMIC_TREE_PATH_SELECTION
export REMTP_DYNAMIC_TREE_FRONTIER_RESCUE
export REMTP_DYNAMIC_TREE_RESCUE_DELTA
export REMTP_DYNAMIC_TREE_RESCUE_MIN_RELATIVE
export REMTP_DYNAMIC_TREE_RESCUE_MIN_TARGET_PROB
export REMTP_DYNAMIC_TREE_EOS_THRESHOLD

# Keep this convenience entrypoint on the same audited runtime path as the
# comparison scripts.  The older direct invocation omitted TREE_ATTN metadata
# and allocated only ``max_depth`` speculative slots, so a tree wider than one
# chain failed on its first target verification step.
export METHOD=dynamic_tree
export MODEL_PATH
export SERVED_MODEL_NAME
export PORT
export MAX_MODEL_LEN
export GPU_MEMORY_UTILIZATION
export ENFORCE_EAGER
export NO_ASYNC_SCHEDULING
export MTP_TOKENS="$REMTP_DYNAMIC_TREE_MAX_DEPTH"
exec "$PROJECT_DIR/scripts/serve_fastmtp_verified.sh"
