#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MTP_TOKENS="${MTP_TOKENS:-6}"
export REMTP_WORKER_CLS=remtp.worker.PrefixCreditMTPWorker
export REMTP_PREFIX_CREDIT_ALLOCATION="${PREFIX_CREDIT_ALLOCATION:-prefix_credit}"
export REMTP_PREFIX_CREDIT_MIN_TOP1_MARGIN="${PREFIX_CREDIT_MIN_TOP1_MARGIN:-0.10}"
export REMTP_PREFIX_CREDIT_PER_TOKEN_TV="${PREFIX_CREDIT_PER_TOKEN_TV:-0.49}"
export REMTP_PREFIX_CREDIT_BLOCK_TV="${PREFIX_CREDIT_BLOCK_TV:-0.75}"
export REMTP_PREFIX_CREDIT_MIN_GAIN_PER_TV="${PREFIX_CREDIT_MIN_GAIN_PER_TV:-0.50}"
export REMTP_PREFIX_CREDIT_COMPILE="${PREFIX_CREDIT_COMPILE:-1}"
export REMTP_PREFIX_CREDIT_DIAGNOSTICS="${PREFIX_CREDIT_DIAGNOSTICS:-0}"
export REMTP_PREFIX_CREDIT_AUDIT_INTERVAL="${PREFIX_CREDIT_AUDIT_INTERVAL:-0}"

exec "$PROJECT_DIR/scripts/serve_probabilistic_mtp.sh"
